# Generated by Django 4.1.1 on 2022-10-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('official_email', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('Contact_person_name', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
            ],
        ),
    ]
