# Generated by Django 4.1.1 on 2022-09-29 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('join_date', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 9, 29, 7, 23, 53, 967294, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
