# Generated by Django 4.1.1 on 2022-09-29 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 7, 29, 9, 495891, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
    ]
