# Generated by Django 4.1.1 on 2022-09-29 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentregister_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 8, 13, 12, 546335, tzinfo=datetime.timezone.utc)),
        ),
    ]
