# Generated by Django 4.1.1 on 2022-10-03 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentregister_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 17, 36, 48, 940125, tzinfo=datetime.timezone.utc)),
        ),
    ]
