# Generated by Django 4.1.1 on 2022-10-12 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_studentregister_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 7, 44, 17, 228773, tzinfo=datetime.timezone.utc)),
        ),
    ]
