# Generated by Django 4.1.1 on 2022-09-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('writer_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('vander_name', models.CharField(max_length=100)),
                ('purchase_date', models.CharField(max_length=100)),
            ],
        ),
    ]
